#!/bin/bash
#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J mpitest
#SBATCH --ntasks-per-node=1
#SBATCH -t 00:30:00

#modules
# module load openmpi

#run the application:
srun ./mpi /pscratch/sd/y/yt634/final_project_dataset/small.csv